import type { NextPage } from 'next';
import Head from 'next/head';
import style from '../../styles/Home.module.scss';

/* Components */

import Controls from '../components/controls';
import CssCopy from '../components/cssCopy';

/* Context */

import { ControlsProvider } from '../context/controlsContext';
import Container from '../components/container';
import Header from '../components/header';

/* Animation */

import AOS from 'aos';
import 'aos/dist/aos.css';
import { useEffect } from 'react';

const Home: NextPage = () => {
  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);
  return (
    <div className={style.app}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ControlsProvider>
        <Header />
        <Container />
        <div
          className={style.flex}
          data-aos='zoom-in-right'
          data-aos-delay='80'
          data-aos-duration='3000'
        >
          <Controls />
          <CssCopy />
        </div>
      </ControlsProvider>
    </div>
  );
};

export default Home;
